//
// Created by prith on 12/21/2016.
//

#ifndef ANDROIDREMOTECONTROL_ENUMS_H
#define ANDROIDREMOTECONTROL_ENUMS_H

enum VIDEO_TYPE
{
    VIDEO_TYPE_INVALID = -1,
    VIDEO_TYPE_1,
    VIDEO_TYPE_2,
    VIDEO_TYPE_3,
    VIDEO_TYPE_MAX
};

enum COMMAND_TYPE
{
    COMMAND_TYPE_INVALID = -1,
    COMMAND_TYPE_START,
    COMMAND_TYPE_STOP,
    COMMAND_TYPE_MAX
};

#endif //ANDROIDREMOTECONTROL_ENUMS_H
